apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oauth2-server

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - configmap-migrations.yaml
  - secret.yaml
  - postgres-pvc.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - flyway-migration-job.yaml
  - ingress.yaml
  - hpa.yaml
  - deployment.yaml
  - service.yaml
  - service-nodeport.yaml

images:
  - name: docker.io/ianlintner068/oauth2-server
    newTag: latest

commonLabels:
  app.kubernetes.io/name: oauth2-server
  app.kubernetes.io/instance: test
