apiVersion: v1
kind: ServiceAccount
metadata:
  name: oauth2-server
  namespace: oauth2-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: oauth2-server
  namespace: oauth2-server
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oauth2-server
  namespace: oauth2-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: oauth2-server
subjects:
  - kind: ServiceAccount
    name: oauth2-server
    namespace: oauth2-server
