apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-server
spec:
  tls:
    - hosts:
        - oauth-staging.example.com
      secretName: oauth2-server-staging-tls
  rules:
    - host: oauth-staging.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oauth2-server
                port:
                  number: 80
