apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oauth2-server-staging

bases:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging

patchesStrategicMerge:
  - ingress-patch.yaml

images:
  - name: ghcr.io/ianlintner/rust_oauth2_server
    newTag: staging
